# Configuration for TANF Calculator

# All states with TANF implementations in PolicyEngine-US
# Note: States use different program names (TANF, TAFDC, TAFI, TFA, etc.)
PILOT_STATES = {
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}

# States with working TANF implementations (all of them)
STATES_WITH_TANF = set(PILOT_STATES.keys())

# States that require county selection (affects benefit calculation)
STATES_REQUIRING_COUNTY = {"CA", "PA", "VA"}

# California counties - format: (enum_name, display_name, region)
# Region 1 = higher cost counties, Region 2 = other counties
CA_COUNTIES = [
    ("ALAMEDA_COUNTY_CA", "Alameda", 1),
    ("ALPINE_COUNTY_CA", "Alpine", 2),
    ("AMADOR_COUNTY_CA", "Amador", 2),
    ("BUTTE_COUNTY_CA", "Butte", 2),
    ("CALAVERAS_COUNTY_CA", "Calaveras", 2),
    ("COLUSA_COUNTY_CA", "Colusa", 2),
    ("CONTRA_COSTA_COUNTY_CA", "Contra Costa", 1),
    ("DEL_NORTE_COUNTY_CA", "Del Norte", 2),
    ("EL_DORADO_COUNTY_CA", "El Dorado", 2),
    ("FRESNO_COUNTY_CA", "Fresno", 2),
    ("GLENN_COUNTY_CA", "Glenn", 2),
    ("HUMBOLDT_COUNTY_CA", "Humboldt", 2),
    ("IMPERIAL_COUNTY_CA", "Imperial", 2),
    ("INYO_COUNTY_CA", "Inyo", 2),
    ("KERN_COUNTY_CA", "Kern", 2),
    ("KINGS_COUNTY_CA", "Kings", 2),
    ("LAKE_COUNTY_CA", "Lake", 2),
    ("LASSEN_COUNTY_CA", "Lassen", 2),
    ("LOS_ANGELES_COUNTY_CA", "Los Angeles", 1),
    ("MADERA_COUNTY_CA", "Madera", 2),
    ("MARIN_COUNTY_CA", "Marin", 1),
    ("MARIPOSA_COUNTY_CA", "Mariposa", 2),
    ("MENDOCINO_COUNTY_CA", "Mendocino", 2),
    ("MERCED_COUNTY_CA", "Merced", 2),
    ("MODOC_COUNTY_CA", "Modoc", 2),
    ("MONO_COUNTY_CA", "Mono", 2),
    ("MONTEREY_COUNTY_CA", "Monterey", 1),
    ("NAPA_COUNTY_CA", "Napa", 1),
    ("NEVADA_COUNTY_CA", "Nevada", 2),
    ("ORANGE_COUNTY_CA", "Orange", 1),
    ("PLACER_COUNTY_CA", "Placer", 2),
    ("PLUMAS_COUNTY_CA", "Plumas", 2),
    ("RIVERSIDE_COUNTY_CA", "Riverside", 2),
    ("SACRAMENTO_COUNTY_CA", "Sacramento", 2),
    ("SAN_BENITO_COUNTY_CA", "San Benito", 2),
    ("SAN_BERNARDINO_COUNTY_CA", "San Bernardino", 2),
    ("SAN_DIEGO_COUNTY_CA", "San Diego", 1),
    ("SAN_FRANCISCO_COUNTY_CA", "San Francisco", 1),
    ("SAN_JOAQUIN_COUNTY_CA", "San Joaquin", 2),
    ("SAN_LUIS_OBISPO_COUNTY_CA", "San Luis Obispo", 1),
    ("SAN_MATEO_COUNTY_CA", "San Mateo", 1),
    ("SANTA_BARBARA_COUNTY_CA", "Santa Barbara", 1),
    ("SANTA_CLARA_COUNTY_CA", "Santa Clara", 1),
    ("SANTA_CRUZ_COUNTY_CA", "Santa Cruz", 1),
    ("SHASTA_COUNTY_CA", "Shasta", 2),
    ("SIERRA_COUNTY_CA", "Sierra", 2),
    ("SISKIYOU_COUNTY_CA", "Siskiyou", 2),
    ("SOLANO_COUNTY_CA", "Solano", 1),
    ("SONOMA_COUNTY_CA", "Sonoma", 1),
    ("STANISLAUS_COUNTY_CA", "Stanislaus", 2),
    ("SUTTER_COUNTY_CA", "Sutter", 2),
    ("TEHAMA_COUNTY_CA", "Tehama", 2),
    ("TRINITY_COUNTY_CA", "Trinity", 2),
    ("TULARE_COUNTY_CA", "Tulare", 2),
    ("TUOLUMNE_COUNTY_CA", "Tuolumne", 2),
    ("VENTURA_COUNTY_CA", "Ventura", 1),
    ("YOLO_COUNTY_CA", "Yolo", 2),
    ("YUBA_COUNTY_CA", "Yuba", 2),
]

# Pennsylvania counties - format: (enum_name, display_name, group)
# 4 county groups with different standard of need amounts
PA_COUNTIES = [
    ("ADAMS_COUNTY_PA", "Adams", 2),
    ("ALLEGHENY_COUNTY_PA", "Allegheny", 2),
    ("ARMSTRONG_COUNTY_PA", "Armstrong", 4),
    ("BEAVER_COUNTY_PA", "Beaver", 3),
    ("BEDFORD_COUNTY_PA", "Bedford", 4),
    ("BERKS_COUNTY_PA", "Berks", 2),
    ("BLAIR_COUNTY_PA", "Blair", 2),
    ("BRADFORD_COUNTY_PA", "Bradford", 2),
    ("BUCKS_COUNTY_PA", "Bucks", 1),
    ("BUTLER_COUNTY_PA", "Butler", 2),
    ("CAMBRIA_COUNTY_PA", "Cambria", 4),
    ("CAMERON_COUNTY_PA", "Cameron", 3),
    ("CARBON_COUNTY_PA", "Carbon", 3),
    ("CENTRE_COUNTY_PA", "Centre", 2),
    ("CHESTER_COUNTY_PA", "Chester", 1),
    ("CLARION_COUNTY_PA", "Clarion", 4),
    ("CLEARFIELD_COUNTY_PA", "Clearfield", 4),
    ("CLINTON_COUNTY_PA", "Clinton", 3),
    ("COLUMBIA_COUNTY_PA", "Columbia", 2),
    ("CRAWFORD_COUNTY_PA", "Crawford", 2),
    ("CUMBERLAND_COUNTY_PA", "Cumberland", 2),
    ("DAUPHIN_COUNTY_PA", "Dauphin", 2),
    ("DELAWARE_COUNTY_PA", "Delaware", 2),
    ("ELK_COUNTY_PA", "Elk", 3),
    ("ERIE_COUNTY_PA", "Erie", 2),
    ("FAYETTE_COUNTY_PA", "Fayette", 4),
    ("FOREST_COUNTY_PA", "Forest", 4),
    ("FRANKLIN_COUNTY_PA", "Franklin", 3),
    ("FULTON_COUNTY_PA", "Fulton", 4),
    ("GREENE_COUNTY_PA", "Greene", 4),
    ("HUNTINGDON_COUNTY_PA", "Huntingdon", 4),
    ("INDIANA_COUNTY_PA", "Indiana", 3),
    ("JEFFERSON_COUNTY_PA", "Jefferson", 4),
    ("JUNIATA_COUNTY_PA", "Juniata", 4),
    ("LACKAWANNA_COUNTY_PA", "Lackawanna", 2),
    ("LANCASTER_COUNTY_PA", "Lancaster", 1),
    ("LAWRENCE_COUNTY_PA", "Lawrence", 3),
    ("LEBANON_COUNTY_PA", "Lebanon", 2),
    ("LEHIGH_COUNTY_PA", "Lehigh", 2),
    ("LUZERNE_COUNTY_PA", "Luzerne", 2),
    ("LYCOMING_COUNTY_PA", "Lycoming", 2),
    ("MCKEAN_COUNTY_PA", "McKean", 3),
    ("MERCER_COUNTY_PA", "Mercer", 3),
    ("MIFFLIN_COUNTY_PA", "Mifflin", 3),
    ("MONROE_COUNTY_PA", "Monroe", 2),
    ("MONTGOMERY_COUNTY_PA", "Montgomery", 1),
    ("MONTOUR_COUNTY_PA", "Montour", 2),
    ("NORTHAMPTON_COUNTY_PA", "Northampton", 2),
    ("NORTHUMBERLAND_COUNTY_PA", "Northumberland", 4),
    ("PERRY_COUNTY_PA", "Perry", 3),
    ("PHILADELPHIA_COUNTY_PA", "Philadelphia", 2),
    ("PIKE_COUNTY_PA", "Pike", 1),
    ("POTTER_COUNTY_PA", "Potter", 3),
    ("SCHUYLKILL_COUNTY_PA", "Schuylkill", 4),
    ("SNYDER_COUNTY_PA", "Snyder", 3),
    ("SOMERSET_COUNTY_PA", "Somerset", 4),
    ("SULLIVAN_COUNTY_PA", "Sullivan", 2),
    ("SUSQUEHANNA_COUNTY_PA", "Susquehanna", 2),
    ("TIOGA_COUNTY_PA", "Tioga", 3),
    ("UNION_COUNTY_PA", "Union", 2),
    ("VENANGO_COUNTY_PA", "Venango", 3),
    ("WARREN_COUNTY_PA", "Warren", 2),
    ("WASHINGTON_COUNTY_PA", "Washington", 3),
    ("WAYNE_COUNTY_PA", "Wayne", 2),
    ("WESTMORELAND_COUNTY_PA", "Westmoreland", 2),
    ("WYOMING_COUNTY_PA", "Wyoming", 2),
    ("YORK_COUNTY_PA", "York", 2),
]

# Virginia counties/cities - format: (enum_name, display_name, group)
# Group 2 = most localities (lower benefits), Group 3 = higher-cost areas
# Note: COLONIAL_HEIGHTS_CITY_VA and MANASSAS_CITY_VA are Group 3 per regulations
# but missing from PolicyEngine enum, so excluded
VA_COUNTIES = [
    ("ACCOMACK_COUNTY_VA", "Accomack", 2),
    ("ALBEMARLE_COUNTY_VA", "Albemarle", 3),
    ("ALEXANDRIA_CITY_VA", "Alexandria", 3),
    ("ALLEGHANY_COUNTY_VA", "Alleghany", 2),
    ("AMELIA_COUNTY_VA", "Amelia", 2),
    ("AMHERST_COUNTY_VA", "Amherst", 2),
    ("APPOMATTOX_COUNTY_VA", "Appomattox", 2),
    ("ARLINGTON_COUNTY_VA", "Arlington", 3),
    ("AUGUSTA_COUNTY_VA", "Augusta", 3),
    ("BATH_COUNTY_VA", "Bath", 2),
    ("BEDFORD_COUNTY_VA", "Bedford", 2),
    ("BLAND_COUNTY_VA", "Bland", 2),
    ("BOTETOURT_COUNTY_VA", "Botetourt", 2),
    ("BRISTOL_CITY_VA", "Bristol", 2),
    ("BRUNSWICK_COUNTY_VA", "Brunswick", 2),
    ("BUCHANAN_COUNTY_VA", "Buchanan", 2),
    ("BUCKINGHAM_COUNTY_VA", "Buckingham", 2),
    ("CAMPBELL_COUNTY_VA", "Campbell", 2),
    ("CAROLINE_COUNTY_VA", "Caroline", 3),
    ("CARROLL_COUNTY_VA", "Carroll", 2),
    ("CHARLES_CITY_COUNTY_VA", "Charles City", 2),
    ("CHARLOTTESVILLE_CITY_VA", "Charlottesville", 3),
    ("CHARLOTTE_COUNTY_VA", "Charlotte", 2),
    ("CHESAPEAKE_CITY_VA", "Chesapeake", 2),
    ("CHESTERFIELD_COUNTY_VA", "Chesterfield", 2),
    ("CLARKE_COUNTY_VA", "Clarke", 2),
    ("CRAIG_COUNTY_VA", "Craig", 2),
    ("CULPEPER_COUNTY_VA", "Culpeper", 2),
    ("CUMBERLAND_COUNTY_VA", "Cumberland", 2),
    ("DANVILLE_CITY_VA", "Danville", 2),
    ("DICKENSON_COUNTY_VA", "Dickenson", 2),
    ("DINWIDDIE_COUNTY_VA", "Dinwiddie", 2),
    ("EMPORIA_CITY_VA", "Emporia", 2),
    ("ESSEX_COUNTY_VA", "Essex", 2),
    ("FAIRFAX_CITY_VA", "Fairfax City", 3),
    ("FAIRFAX_COUNTY_VA", "Fairfax", 3),
    ("FALLS_CHURCH_CITY_VA", "Falls Church", 3),
    ("FAUQUIER_COUNTY_VA", "Fauquier", 3),
    ("FLOYD_COUNTY_VA", "Floyd", 2),
    ("FLUVANNA_COUNTY_VA", "Fluvanna", 2),
    ("FRANKLIN_CITY_VA", "Franklin City", 2),
    ("FRANKLIN_COUNTY_VA", "Franklin", 2),
    ("FREDERICKSBURG_CITY_VA", "Fredericksburg", 3),
    ("FREDERICK_COUNTY_VA", "Frederick", 2),
    ("GILES_COUNTY_VA", "Giles", 2),
    ("GLOUCESTER_COUNTY_VA", "Gloucester", 2),
    ("GOOCHLAND_COUNTY_VA", "Goochland", 2),
    ("GRAYSON_COUNTY_VA", "Grayson", 2),
    ("GREENE_COUNTY_VA", "Greene", 2),
    ("GREENSVILLE_COUNTY_VA", "Greensville", 2),
    ("HALIFAX_COUNTY_VA", "Halifax", 2),
    ("HAMPTON_CITY_VA", "Hampton", 3),
    ("HANOVER_COUNTY_VA", "Hanover", 2),
    ("HARRISONBURG_CITY_VA", "Harrisonburg", 2),
    ("HENRICO_COUNTY_VA", "Henrico", 2),
    ("HENRY_COUNTY_VA", "Henry", 2),
    ("HIGHLAND_COUNTY_VA", "Highland", 2),
    ("HOPEWELL_CITY_VA", "Hopewell", 2),
    ("ISLE_OF_WIGHT_COUNTY_VA", "Isle of Wight", 2),
    ("JAMES_CITY_COUNTY_VA", "James City", 3),
    ("KING_AND_QUEEN_COUNTY_VA", "King and Queen", 2),
    ("KING_GEORGE_COUNTY_VA", "King George", 3),
    ("KING_WILLIAM_COUNTY_VA", "King William", 2),
    ("LANCASTER_COUNTY_VA", "Lancaster", 2),
    ("LEE_COUNTY_VA", "Lee", 2),
    ("LEXINGTON_CITY_VA", "Lexington", 2),
    ("LOUDOUN_COUNTY_VA", "Loudoun", 2),
    ("LOUISA_COUNTY_VA", "Louisa", 2),
    ("LUNENBURG_COUNTY_VA", "Lunenburg", 2),
    ("LYNCHBURG_CITY_VA", "Lynchburg", 2),
    ("MADISON_COUNTY_VA", "Madison", 2),
    ("MANASSAS_PARK_CITY_VA", "Manassas Park", 3),
    ("MATHEWS_COUNTY_VA", "Mathews", 2),
    ("MECKLENBURG_COUNTY_VA", "Mecklenburg", 2),
    ("MIDDLESEX_COUNTY_VA", "Middlesex", 2),
    ("MONTGOMERY_COUNTY_VA", "Montgomery", 3),
    ("NELSON_COUNTY_VA", "Nelson", 2),
    ("NEWPORT_NEWS_CITY_VA", "Newport News", 3),
    ("NEW_KENT_COUNTY_VA", "New Kent", 2),
    ("NORFOLK_CITY_VA", "Norfolk", 2),
    ("NORTHAMPTON_COUNTY_VA", "Northampton", 2),
    ("NORTHUMBERLAND_COUNTY_VA", "Northumberland", 2),
    ("NORTON_CITY_VA", "Norton", 2),
    ("NOTTOWAY_COUNTY_VA", "Nottoway", 2),
    ("ORANGE_COUNTY_VA", "Orange", 2),
    ("PAGE_COUNTY_VA", "Page", 2),
    ("PATRICK_COUNTY_VA", "Patrick", 2),
    ("PETERSBURG_CITY_VA", "Petersburg", 2),
    ("PITTSYLVANIA_COUNTY_VA", "Pittsylvania", 2),
    ("POQUOSON_CITY_VA", "Poquoson", 3),
    ("PORTSMOUTH_CITY_VA", "Portsmouth", 2),
    ("POWHATAN_COUNTY_VA", "Powhatan", 2),
    ("PRINCE_EDWARD_COUNTY_VA", "Prince Edward", 2),
    ("PRINCE_GEORGE_COUNTY_VA", "Prince George", 2),
    ("PRINCE_WILLIAM_COUNTY_VA", "Prince William", 3),
    ("PULASKI_COUNTY_VA", "Pulaski", 2),
    ("RADFORD_CITY_VA", "Radford", 2),
    ("RAPPAHANNOCK_COUNTY_VA", "Rappahannock", 2),
    ("RICHMOND_CITY_VA", "Richmond City", 2),
    ("RICHMOND_COUNTY_VA", "Richmond", 2),
    ("ROANOKE_CITY_VA", "Roanoke City", 2),
    ("ROANOKE_COUNTY_VA", "Roanoke", 2),
    ("ROCKBRIDGE_COUNTY_VA", "Rockbridge", 2),
    ("ROCKINGHAM_COUNTY_VA", "Rockingham", 2),
    ("RUSSELL_COUNTY_VA", "Russell", 2),
    ("SCOTT_COUNTY_VA", "Scott", 2),
    ("SHENANDOAH_COUNTY_VA", "Shenandoah", 2),
    ("SMYTH_COUNTY_VA", "Smyth", 2),
    ("SOUTHAMPTON_COUNTY_VA", "Southampton", 2),
    ("SPOTSYLVANIA_COUNTY_VA", "Spotsylvania", 3),
    ("STAFFORD_COUNTY_VA", "Stafford", 3),
    ("STAUNTON_CITY_VA", "Staunton", 3),
    ("SUFFOLK_CITY_VA", "Suffolk", 2),
    ("SURRY_COUNTY_VA", "Surry", 2),
    ("SUSSEX_COUNTY_VA", "Sussex", 2),
    ("TAZEWELL_COUNTY_VA", "Tazewell", 2),
    ("VIRGINIA_BEACH_CITY_VA", "Virginia Beach", 2),
    ("WARREN_COUNTY_VA", "Warren", 2),
    ("WASHINGTON_COUNTY_VA", "Washington", 2),
    ("WAYNESBORO_CITY_VA", "Waynesboro", 3),
    ("WESTMORELAND_COUNTY_VA", "Westmoreland", 2),
    ("WISE_COUNTY_VA", "Wise", 2),
    ("WYTHE_COUNTY_VA", "Wythe", 2),
    ("YORK_COUNTY_VA", "York", 3),
]

# Default year for calculations
DEFAULT_YEAR = 2025
